---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg
    - software-properties-common

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present
    update_cache: yes

- name: Install Consul
  apt:
    name: consul
    state: present

- name: Create directories for Consul
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul

- name: Copy Consul config
  copy:
    src: /tmp/consul_server.hcl
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul

- name: Create systemd service for Consul
  copy:
    content: |
      [Unit]
      Description=Consul agent
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      User=consul
      Group=consul
      ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
      Restart=always
      RestartSec=5
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/consul.service
    mode: 0644

- name: Start and enable Consul
  systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes