---
- name: Install dependencies
  apt:
    name: 
      - curl
      - gnupg
      - software-properties-common
      - jq
      - python3-pip
    state: present
    update_cache: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    extra_args: --root-user-action=ignore

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
    - /etc/consul.d
    - /opt/consul
    - /var/log/consul

# Исправленный путь
- name: Copy Consul config
  template:
    src: "/vagrant/src/consul01/consul_server.hcl"
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
  notify: restart consul

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Consul agent
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      User=consul
      Group=consul
      ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d/
      Restart=always
      RestartSec=5
      LimitNOFILE=65536
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/consul.service
    mode: 0644
  notify: restart consul

- name: Start and enable Consul
  systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes

# Добавляем обработчики
handlers:
  - name: restart consul
    systemd:
      name: consul
      state: restarted
      daemon_reload: yes