---
- name: Create directories for Consul
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755
  loop:
    - /etc/consul.d
    - /opt/consul

- name: Download Consul
  unarchive:
    src: https://releases.hashicorp.com/consul/1.15.3/consul_1.15.3_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes

- name: Copy server config
  template:
    src: consul_server.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0640

- name: Start and enable Consul service
  systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes