Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Сервер Consul
  config.vm.define "consul_server" do |consul_server|
    consul_server.vm.hostname = "consul-server"
    consul_server.vm.network "private_network", ip: "192.168.56.10"
  end

  # Менеджер (для доступа к UI)
  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.11"
    manager.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "0.0.0.0"
  end

  # API Сервис
  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.56.20"
    api.vm.network "forwarded_port", guest: 8082, host: 8082, host_ip: "0.0.0.0"
  end

  # База данных
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.30"
  end

  # Подготовка окружения
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y python3 python3-pip python3-setuptools
    pip3 install --upgrade pip
    pip3 install ansible
    apt-get install -y rsync
    ufw --force disable
  SHELL
end
