---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes

# Исправление для Ubuntu 20.04 (PostgreSQL 12)
- name: Configure PostgreSQL
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: '^{{ item.regexp }}'
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - { regexp: '^listen_addresses\s*=', line: "listen_addresses = '*'" }
    - { regexp: '^max_connections\s*=', line: "max_connections = 200" }
  notify: restart postgresql

- name: Configure client authentication
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    line: "host    all             all             192.168.60.0/24           md5"
    backup: yes
  notify: restart postgresql

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: hotels_db
    state: present
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'

- name: Create user
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_user | default('hotel_user') }}"
    password: "{{ postgres_password | default('securepassword') }}"
    state: present
    role_attr_flags: "CREATEDB,LOGIN"

- name: Create table
  become_user: postgres
  postgresql_query:
    db: hotels_db
    query: |
      CREATE TABLE IF NOT EXISTS hotels (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        address VARCHAR(255) NOT NULL,
        rating INTEGER NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
      );

- name: Insert sample data
  become_user: postgres
  postgresql_query:
    db: hotels_db
    query: |
      INSERT INTO hotels (name, address, rating) 
      VALUES 
        ('Hotel California', 'California', 4), 
        ('Grand Budapest Hotel', 'Budapest', 5), 
        ('The Plaza', 'New York', 5)
      ON CONFLICT (name) DO NOTHING;

handlers:
  - name: restart postgresql
    service:
      name: postgresql
      state: restarted