- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: hotels_db
    state: present

- name: Create user
  become_user: postgres
  postgresql_user:
    name: hotel_user
    password: "securepassword"
    state: present

- name: Create table and insert data
  become_user: postgres
  postgresql_query:
    db: hotels_db
    query: |
      CREATE TABLE IF NOT EXISTS hotels (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        location VARCHAR(100)
      );
      INSERT INTO hotels (name, location) 
      VALUES 
        ('Hotel California', 'California'), 
        ('Grand Budapest Hotel', 'Budapest'), 
        ('The Plaza', 'New York');