---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: yes

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create application user
  become_user: postgres
  postgresql_user:
    name: hotel_user
    password: hotel_password
    role_attr_flags: "CREATEDB,LOGIN"
  become: yes

- name: Create application database
  become_user: postgres
  postgresql_db:
    name: hotels_db
    owner: hotel_user
    encoding: UTF8
    lc_ctype: en_US.UTF-8
    lc_collate: en_US.UTF-8
  become: yes

- name: Find PostgreSQL config directory
  find:
    paths: /etc/postgresql
    patterns: "main"
    file_type: directory
  register: postgres_config_dirs
  become: yes

- name: Configure remote access
  lineinfile:
    path: "{{ item.path }}/postgresql.conf"
    regexp: "^listen_addresses"
    line: "listen_addresses = '*'"
  loop: "{{ postgres_config_dirs.files }}"
  become: yes
  notify: restart postgresql

- name: Configure client authentication
  lineinfile:
    path: "{{ item.path }}/pg_hba.conf"
    line: "host all all 0.0.0.0/0 md5"
  loop: "{{ postgres_config_dirs.files }}"
  become: yes
  notify: restart postgresql

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  become: yes
  when: false  # Handled by notify
