- name: Install Docker and dependencies
  block:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

- name: Configure Docker
  block:
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Reset ssh connection
      meta: reset_connection

- name: Setup project directory
  file:
    path: /opt/microservices
    state: directory
    mode: 0755

- name: Deploy application files
  copy:
    src: "{{ item }}"
    dest: /opt/microservices/
    mode: "{{ '0755' if 'init-db.sh' in item else '0644' }}"
  loop:
    - docker-compose.yml
    - init-db.sh

- name: Start services
  community.docker.docker_compose_v2:
    project_src: /opt/microservices
    build: always
    pull: if_not_present
    state: present