---
- name: Установка Consul сервера
  hosts: consul_server
  become: yes
  roles:
    - install_consul_server

- name: Установка Consul клиента на manager
  hosts: manager
  become: yes
  roles:
    - install_consul_manager

- name: Установка Consul клиента на API
  hosts: api
  become: yes
  roles:
    - install_consul_client

- name: Установка Consul клиента на DB
  hosts: db
  become: yes
  roles:
    - install_consul_client

- name: Установка базы данных
  hosts: db
  become: yes
  roles:
    - install_db

- name: Ожидание запуска базы данных
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Пауза для запуска PostgreSQL
      pause:
        seconds: 30

- name: Установка сервиса отелей
  hosts: api
  become: yes
  roles:
    - install_hotels_service

- name: Финальная проверка сервисов
  hosts: api
  become: yes
  tasks:
    - name: Установка net-tools для проверки портов
      apt:
        name: net-tools
        state: present

    - name: Проверка портов
      shell: netstat -tlnp | grep -E ':(8082|8500)'
      register: ports_check
      ignore_errors: yes
    
    - name: Вывод открытых портов
      debug:
        var: ports_check.stdout_lines

    - name: Проверка статуса hotel-service
      shell: systemctl status hotel-service --no-pager
      register: service_status
      ignore_errors: yes
    
    - name: Вывод статуса сервиса
      debug:
        var: service_status.stdout_lines

    - name: Ожидание полного запуска сервиса
      pause:
        seconds: 15

    - name: Финальная проверка портов после паузы
      shell: netstat -tlnp | grep -E ':(8082|8500)'
      register: final_ports_check
      ignore_errors: yes
    
    - name: Вывод финальных портов
      debug:
        var: final_ports_check.stdout_lines

    - name: Проверка логов hotel-service
      shell: journalctl -u hotel-service --no-pager -n 20
      register: service_logs
      ignore_errors: yes
    
    - name: Вывод логов сервиса
      debug:
        var: service_logs.stdout_lines
