---
- name: Fix SSH access
  hosts: all
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: 0700

    - name: Add manager public key
      ansible.posix.authorized_key:
        user: vagrant
        key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"
        state: present
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"
      
    - name: Disable strict host key checking
      lineinfile:
        path: /etc/ssh/ssh_config
        line: "    StrictHostKeyChecking no"
        insertafter: "^Host \\*"
        state: present
      notify: Restart SSH
      
  handlers:
    - name: Restart SSH
      systemd:
        name: ssh
        state: restarted
