Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  # Общая синхронизация конфигов Consul
  config.vm.synced_folder "../consul01", "/vagrant/consul"

  config.vm.define "consul_server" do |server|
    server.vm.hostname = "consul-server"
    server.vm.network "private_network", ip: "192.168.60.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Копирование конфига сервера
    server.vm.provision "file", 
      source: "../consul01/consul_server.hcl", 
      destination: "/tmp/consul_server.hcl"
  end

  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.60.11"
    api.vm.network "forwarded_port", guest: 8080, host: 8082
    api.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    # Копирование конфига клиента
    api.vm.provision "file", 
      source: "../consul01/consul_client_api.hcl", 
      destination: "/tmp/consul_client.hcl"
  end

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.60.12"
    manager.vm.network "forwarded_port", guest: 8500, host: 8500
    manager.vm.synced_folder ".", "/home/vagrant/ansible"
    manager.vm.synced_folder "../consul01", "/home/vagrant/consul"
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.60.13"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Копирование конфига клиента
    db.vm.provision "file", 
      source: "../consul01/consul_client_db.hcl", 
      destination: "/tmp/consul_client.hcl"
  end

  # Общий провижионинг для всех машин
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip python3-setuptools rsync
    pip3 install --upgrade pip
    pip3 install ansible
    ufw --force disable
  SHELL
end