Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    
    config.vm.define "consul_server" do |server|
      server.vm.hostname = "consul-server"
      server.vm.network "private_network", ip: "192.168.60.10"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  
    config.vm.define "api" do |api|
      api.vm.hostname = "api"
      api.vm.network "private_network", ip: "192.168.60.11"
      api.vm.network "forwarded_port", guest: 8080, host: 8888
      api.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
  
    config.vm.define "manager" do |manager|
      manager.vm.hostname = "manager"
      manager.vm.network "private_network", ip: "192.168.60.12"
      manager.vm.network "forwarded_port", guest: 8500, host: 8765
      manager.vm.synced_folder "../ansible02", "/home/vagrant/ansible"
      manager.vm.synced_folder "../consul01", "/home/vagrant/consul"
      manager.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  
    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.60.13"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  end
