- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create test page
  copy:
    content: "<html><body><h1>Apache configuring by bartonjo 25_04_kzn working on {{ ansible_hostname }}</h1></body></html>"
    dest: /var/www/html/index.html