---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - gnupg
    - software-properties-common
    - jq
    - net-tools
  tags: packages

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: repo

- name: Install Consul
  apt:
    name: consul
    state: present
    allow_unauthenticated: yes
    install_recommends: no
  tags: consul

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
    - /etc/consul.d
    - /opt/consul
    - /var/log/consul
  tags: dirs

- name: Copy Consul config
  copy:
    src: /tmp/consul_client.hcl
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
  notify: restart consul
  tags: config

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Consul agent
      After=network-online.target
      Wants=network-online.target
      
      [Service]
      User=consul
      Group=consul
      ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
      Restart=always
      RestartSec=5
      LimitNOFILE=65536
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/consul.service
    mode: 0644
  notify: restart consul
  tags: service

- name: Start and enable Consul
  systemd:
    name: consul
    state: started
    enabled: yes
    daemon_reload: yes
  tags: start

- name: Download Envoy
  get_url:
    url: https://github.com/envoyproxy/envoy/releases/download/v1.25.10/envoy-1.25.10-linux-x86_64
    dest: /usr/local/bin/envoy
    mode: '0755'
    timeout: 30
    validate_certs: no
  tags: envoy

- name: Create envoy user
  user:
    name: envoy
    system: yes
    group: envoy
    shell: /bin/false
    home: /nonexistent
  tags: user

- name: Register services
  template:
    src: "{{ item }}.j2"
    dest: /etc/consul.d/{{ item }}.json
    owner: consul
    group: consul
  with_items:
    - "postgres-service"
    - "hotels-service"
  notify: restart consul
  tags: services

- name: Optimize system limits
  pam_limits:
    domain: envoy
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { type: 'soft', item: 'nofile', value: 65536 }
    - { type: 'hard', item: 'nofile', value: 65536 }
    - { type: 'soft', item: 'memlock', value: 'unlimited' }
    - { type: 'hard', item: 'memlock', value: 'unlimited' }
  tags: limits