- name: Install OpenJDK
  apt:
    name: openjdk-11-jdk-headless
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  tags: java

- name: Create service user
  user:
    name: hoteluser
    system: yes
    group: hoteluser
    home: /opt/hotel
  tags: user

- name: Copy application
  copy:
    src: "/home/vagrant/services/hotel-service/target/hotel-service.jar"
    dest: "/opt/hotel/hotel-service.jar"
    owner: hoteluser
    group: hoteluser
    mode: '0644'
  tags: app

- name: Create environment file
  copy:
    content: |
      JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled"
      POSTGRES_HOST="127.0.0.1"
      POSTGRES_PORT="5432"
      POSTGRES_DB="hotels_db"
      POSTGRES_USER="hotel_user"
      POSTGRES_PASSWORD="securepassword"
      CONSUL_HOST="consul-server"
      CONSUL_PORT="8500"
      SERVER_PORT=8080
    dest: /etc/hotel-service.env
  tags: env

- name: Create systemd service
  template:
    src: hotel-service.service.j2
    dest: /etc/systemd/system/hotel-service.service
    mode: 0644
  tags: service

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags: reload

- name: Start hotel service
  systemd:
    name: hotel-service
    state: started
    enabled: yes
  tags: start

- name: Enable JVM monitoring
  template:
    src: jmx_exporter.conf.j2
    dest: /opt/hotel/jmx_exporter.conf
    owner: hoteluser
    group: hoteluser
  tags: monitoring