---
- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  become: yes

- name: Create application directory
  file:
    path: /opt/hotel-service
    state: directory
    mode: 0755
  become: yes

- name: Copy application JAR
  copy:
    src: "{{ lookup('env', 'PWD') }}/files/hotel-service.jar"
    dest: /opt/hotel-service/hotel-service.jar
    mode: 0644
  become: yes

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Hotels Service
      After=network.target consul.service
      
      [Service]
      User=root
      Group=root
      EnvironmentFile=/etc/environment
      ExecStart=/usr/bin/java -jar /opt/hotel-service/hotel-service.jar
      Restart=always
      RestartSec=5
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/hotel-service.service
    mode: 0644
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Start and enable service
  systemd:
    name: hotel-service
    state: started
    enabled: yes
  become: yes