- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present

- name: Copy application
  copy:
    src: /path/to/hotel-service.jar
    dest: /opt/hotel-service.jar

- name: Create environment file
  copy:
    content: |
      POSTGRES_HOST="127.0.0.1"
      POSTGRES_PORT="5432"
      POSTGRES_DB="hotels_db"
      POSTGRES_USER="hotel_user"
      POSTGRES_PASSWORD="securepassword"
    dest: /etc/hotel-service.env

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Hotel Service
      After=network.target
      
      [Service]
      EnvironmentFile=/etc/hotel-service.env
      ExecStart=/usr/bin/java -jar /opt/hotel-service.jar
      User=hoteluser
      Restart=always
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/hotel-service.service

- name: Start hotel service
  systemd:
    name: hotel-service
    state: started
    enabled: yes
    daemon_reload: yes