---
- name: Install OpenJDK
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Create service user
  user:
    name: hotels
    system: yes
    group: hotels
    home: /opt/hotels-service

- name: Copy application
  copy:
    src: "hotel-service.jar"
    dest: "/opt/hotels-service/hotel-service.jar"
    owner: hotels
    group: hotels
    mode: '0644'

- name: Configure environment
  template:
    src: "hotels-service.env.j2"
    dest: /etc/default/hotels-service
    owner: hotels
    group: hotels

- name: Create systemd service
  copy:
    content: |
      [Unit]
      Description=Hotels Service
      After=network.target consul.service
      
      [Service]
      EnvironmentFile=/etc/default/hotels-service
      ExecStart=/usr/bin/java -jar /opt/hotels-service/hotel-service.jar
      User=hotels
      Group=hotels
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/hotels-service.service
    mode: 0644
  notify: restart hotel-service

- name: Start and enable service
  systemd:
    name: hotels-service
    state: started
    enabled: yes
    daemon_reload: yes

handlers:
  - name: restart hotel-service
    systemd:
      name: hotels-service
      state: restarted
      daemon_reload: yes