---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create test database using template0
  become: yes
  command: sudo -u postgres createdb testdb -E UTF8 --template=template0 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8

- name: Create sample table
  become: yes
  command: >
    sudo -u postgres psql -d testdb -c 
    "CREATE TABLE IF NOT EXISTS sample_data (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      value TEXT
    );"

- name: Insert sample data
  become: yes
  command: >
    sudo -u postgres psql -d testdb -c 
    "INSERT INTO sample_data (name, value) VALUES
      ('Item 1', 'Value 1'),
      ('Item 2', 'Value 2'),
      ('Item 3', 'Value 3');"